### ISSUE TITLE
Cannot read property 'adjust_window_size' of undefined

### ISSUE THREAD

**Issue by zeke** [rhysd/electron-about-window#18]
Hi @rhysd 👋 

I'm trying to add an about menu to https://github.com/beakerbrowser/beaker and seeing this error:

<img width="532" alt="screen shot 2018-02-17 at 6 54 40 pm" src="https://user-images.githubusercontent.com/2289/36347747-0650b6f4-1414-11e8-869b-6313f631889b.png">

The app is using the new ES import style which is a bit unfamiliar to me:

```js
import {default as openAboutWindow} from 'electron-about-window'
```

Is what I'm doing now, and:

```js
{
  label: 'Beaker',
  submenu: [
    {
      label: 'About This App',
      click () { openAboutWindow() }
    }
}
```

Any ideas what I'm doing wrong?

**Comment by rhysd** [comment]
Hi!

The first argument of `openAboutWindow()` is not optional. It must be an object, and `icon_path` key is also required. This is because there is no way to get a path to icon image file automatically.

Please look at a table in README.md for the details of the parameter.

https://github.com/rhysd/electron-about-window#parameters-properties-of-openaboutwindow

**Comment by zeke** [comment]
Thanks I'll give that a try.

**Comment by zeke** [comment]
Worked! 

I think there should be a more useful error though. Maybe if no object is passed, a descriptive error should be thrown.

**Comment by rhysd** [comment]
Would be better. Thank you for suggestion.

**Comment by zeke** [comment]
👏
