### ISSUE TITLE
package.json not used if in a different directory

### ISSUE THREAD

**Issue by usergit** [rhysd/electron-about-window#23]
I currently have a directory structure like this

```
mainFolder
  subFolder
    assets
      logo.png
    main.js
  package.json
```

in main.js I have this code

`click: () => openAboutWindow({
            icon_path: join(__dirname, '/assets/logo.png'),
            copyright: 'Copyright (c) 2018 www.example.com',
            package_json_dir: join(__dirname, '..')
          })`

but the generic electron icon is loaded without the attributes that are in package.json

if main.js is moved back to mainFolder, everything works as expected

**Comment by rhysd** [comment]
https://github.com/rhysd/electron-about-window/blob/master/src/index.ts#L15

I could not find any problem with your code and my implementation.

Could you check this warning message here?: https://github.com/rhysd/electron-about-window/blob/master/src/index.ts#L21

**Comment by usergit** [comment]
that error message is not displayed in the terminal

**Comment by rhysd** [comment]
weird... In example, I used the same props and it works.

https://github.com/rhysd/electron-about-window/blob/master/example/main.js#L28-L33

Well, is the project in public? If it's just a trial, is it possible to send your project codes to me? (logo can be dummy because it's not related to this issue)
It's very important to reproduce the problem in my side.

**Comment by usergit** [comment]
after much trial and error I decided to start fresh, and everything works as expected. Thanks for the help
